### ISSUE TITLE
Problems running `npm run deploy`

### ISSUE THREAD

**Issue by FrankR85** [cloudflare/cobol-worker#1]
I just wanted to try out the example and publish this repository to my worker.
However, running `npm run deploy` as explained [here](https://blog.cloudflare.com/cloudflare-workers-now-support-cobol/) gives me this error:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.11.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy'
1 verbose cli ]
2 info using npm@6.11.3
3 info using node@v12.11.1
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle @1.0.0~predeploy: @1.0.0
6 verbose lifecycle @1.0.0~predeploy: unsafe-perm in lifecycle true
7 verbose lifecycle @1.0.0~predeploy: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/frank/Repositories/cloudflare/cobol-worker/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
8 verbose lifecycle @1.0.0~predeploy: CWD: /Users/frank/Repositories/cloudflare/cobol-worker
9 silly lifecycle @1.0.0~predeploy: Args: [ '-c', 'bash build.sh' ]
10 silly lifecycle @1.0.0~predeploy: Returned: code: 1  signal: null
11 info lifecycle @1.0.0~predeploy: Failed to exec predeploy script
12 verbose stack Error: @1.0.0 predeploy: `bash build.sh`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
12 verbose stack     at EventEmitter.emit (events.js:210:5)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:210:5)
12 verbose stack     at maybeClose (internal/child_process.js:1021:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
13 verbose pkgid @1.0.0
14 verbose cwd /Users/frank/Repositories/cloudflare/cobol-worker
15 verbose Darwin 19.3.0
16 verbose argv "/usr/local/Cellar/node/12.11.1/bin/node" "/usr/local/bin/npm" "run" "deploy"
17 verbose node v12.11.1
18 verbose npm  v6.11.3
19 error code ELIFECYCLE
20 error errno 1
21 error @1.0.0 predeploy: `bash build.sh`
21 error Exit status 1
22 error Failed at the @1.0.0 predeploy script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]
```

Any ideas what I am doing wrong?

**Comment by FrankR85** [comment]
Maybe related is this error with `wrangler publish`:
```
~/Repositories/cloudflare/cobol-worker $ wrangler publish
⬇️ Installing wranglerjs...
⬇️ Installing wasm-pack...
👀  ./build/out.js 3:25
Module parse failed: Unexpected token (3:25)
You may need an appropriate loader to handle this file type.
| 
| var Module = (function() {
>   var _scriptDir = import.meta.url;
|   
|   return (
 @ ./src/index.js 1:0-32 14:4-6
Error: webpack returned an error. Try configuring `entry` in your webpack config relative to the current working directory, or setting `context = __dirname` in your webpack config.
```
